apiVersion: v1
kind: DeploymentConfig
metadata:
  labels:
    app: willieweb
	location: dal13
	creater: willie
  name: willieweb
spec:
  replicas: 2
strategy:
  activeDeadlineSeconds: 21600
  rollingParams:
    intervalSeconds: 1
    maxSurge: 25%
    maxUnavailable: 25%
    timeoutSeconds: 600
    updatePeriodSeconds: 1
  type: Rolling  
template:
  metadata:
    app: willieweb
	location: dal13
	creater: willie  
  spec:
    containers:
      image: ikubernetes/myapp:v1
      imagePullPolicy: IfNotPresent
      name: willieweb
      ports:
        -containerPort: 8080
         protocol: TCP
         







