apiVersion: v1
kind: DeploymentConfig
metadata:
  labels:
    app: willieweb
    location: dal13
    creator: willie
  name: willieweb
spec:
  replicas: 2
  selector:
    app: willieweb
    location: dal13
    creator: willie
  strategy:
    activeDeadlineSeconds: 21600
    rollingParams:
      intervalSeconds: 1
      maxSurge: 25%
      maxUnavailable: 25%
      timeoutSeconds: 600
      updatePeriodSeconds: 1
    type: Rolling  
  template:
    metadata:
      labels:
        app: willieweb
        location: dal13
        creator: willie 
    spec:
      containers:
      - image: ikubernetes/mini-http-server:latest
        imagePullPolicy: IfNotPresent
        name: willieweb
        ports:
        - containerPort: 18080
          protocol: TCP
         







