apiVersion: v1
kind: Service
metadata:
  name: willieweb-service
spec:
  ports:
    - name: 18080-tcp
      port: 18080
      targetPort: 18080
  selector:
    app: willieweb
    location: dal13
    creator: willie